"""Initial revision

Revision ID: 850c4a1036ca
Revises: c7f4b47ddd31
Create Date: 2024-09-27 12:06:14.424519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '850c4a1036ca'
down_revision: Union[str, None] = 'c7f4b47ddd31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
